ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json

# RUN wget https://jdbc.postgresql.org/download/postgresql-42.6.0.jar /usr/share/logstash/config/